name: nrnr
description: nrnr

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flutter_svg: ^0.16.1
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  carousel_slider: ^1.4.1
  infinite_listview: ^1.0.1+1
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  dio: ^2.0.9
  image_picker: ^0.6.3+4
  multi_image_picker: ^4.6.1
  email_validator: ^1.0.0
  flutter_plugin_android_lifecycle: ^1.0.6

  flutter_candies_demo_library:
    git:
      url: https://github.com/fluttercandies/flutter_candies_demo_library.git



dev_dependencies:
  flutter_test:
      sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/loading.gif
   - assets/background.jpeg
   - assets/images/background.svg
   - assets/images/loginButton.svg
   - assets/images/signupButton.svg
   - assets/top_background.svg
   - assets/top_background.png
   - assets/images/circle.svg
   - assets/images/logo.png
   - assets/images/sign_bar.png
   - assets/images/signup.png
   - assets/images/logo_text.png
   - assets/images/signin_btn.svg
   - assets/images/circle_background.png
   - assets/images/person_background.png
   - assets/images/newLogo.png
   - assets/images/newLogin.png
   - assets/images/newLogin.svg
   - assets/images/done.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
