class Autogenerated {
  int id;
  String name;
  String hash;
  String sha256;
  String ext;
  String mime;
  String size;
  String url;
  String provider;
  Null publicId;
  int createdAt;
  int updatedAt;
  List<Null> related;

  Autogenerated(
      {this.id,
        this.name,
        this.hash,
        this.sha256,
        this.ext,
        this.mime,
        this.size,
        this.url,
        this.provider,
        this.publicId,
        this.createdAt,
        this.updatedAt,
        this.related});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    hash = json['hash'];
    sha256 = json['sha256'];
    ext = json['ext'];
    mime = json['mime'];
    size = json['size'];
    url = json['url'];
    provider = json['provider'];
    publicId = json['public_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    related = json['reated'];

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['hash'] = this.hash;
    data['sha256'] = this.sha256;
    data['ext'] = this.ext;
    data['mime'] = this.mime;
    data['size'] = this.size;
    data['url'] = this.url;
    data['provider'] = this.provider;
    data['public_id'] = this.publicId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['related'] = this.related;
    return data;
  }



}
